Import('*')

# get string of absolute of cwd
sconscript_cwd = Dir('.').srcnode().abspath

# include locations
includes += [sconscript_cwd+'/include']
includes += [sconscript_cwd+'/include/arm']
includes += [sconscript_cwd+'/include/cmsis']
includes += [sconscript_cwd+'/include/cortexm']
includes += [sconscript_cwd+'/include/diag']
includes += [sconscript_cwd+'/include/stm32f4xx']

# source locations
sources += Glob('src/cmsis/*.c')
sources += Glob('src/cortexm/*.c')
sources += Glob('src/diag/*.c')
sources += Glob('src/newlib/*.c')
